version: '3'

services:
  web-prod:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.prod
    ports:
      - '${PORT}:80'
    environment:
      NEXT_SHARP_PATH: ${NEXT_SHARP_PATH}
      PORT: 80
      STAGE: ${STAGE}
