version: '3'

services:
  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - '${PORT}:${PORT}'
    stdin_open: true
    tty: true
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    environment:
      MACHINE: docker
      NEXT_SHARP_PATH: ${NEXT_SHARP_PATH}
      PORT: ${PORT}
      STAGE: ${STAGE}
