version: '3'

services:
  serverless:
    build: .
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      CHOKIDAR_USEPOLLING: true
      LOCAL: ${LOCAL}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
