name: NPM Publish
on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main

      - uses: actions/setup-node@v3
        with:
          node-version: 16.13.0
          registry-url: 'https://registry.npmjs.org'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM }}

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 7.0.1

      - name: Install & Build
        run: |
          pnpm install --frozen-lockfile --ignore-scripts  
          pnpm build

      - name: Publish
        run: |
          pnpm publish --access=public
