name: Create Release
on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Conventional Changelog
        uses: TriPSs/conventional-changelog-action@v3
        id: changelog
        with:
          git-message: 'chore(release): {version} [no ci]'
          git-user-email: rialcantara21@gmail.com
          git-user-name: Rodrick Alcantara
          github-token: ${{ secrets.PAT }}
          output-file: 'false'

      - name: Create New Release
        uses: actions/create-release@v1
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          release_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
